name: Pipeline-unit-tests-backend

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Install Dependencies
        working-directory: api
        run: npm install

      - name: Run Backend Tests
        working-directory: api
        run: npm run test